<?php

defined('ABSPATH') || exit;

const STV_CLASS_UNCLASSIFIED = 0;
const STV_CLASS_KNOWN_AI_CRAWLER = 1;
const STV_CLASS_ODD_USER_AGENT = 2;
const STV_CLASS_SUSPICIOUS_CLIENT = 3;
const STV_CLASS_SUSPICIOUS_DM8 = 4;

const STV_REASON_NONE = 0;
const STV_REASON_KNOWN_AI = 1 << 0;
const STV_REASON_ODD_UA = 1 << 1;
const STV_REASON_MISSING_SEC_FETCH = 1 << 2;
const STV_REASON_OLD_BROWSER_VERSION = 1 << 3;
const STV_REASON_DM8 = 1 << 4;
const STV_REASON_HTTP_404 = 1 << 5;
const STV_REASON_HTTP_410 = 1 << 6;
